spring:
  datasource:
    url: jdbc:mysql://database-my-blog.c1uyawmgs9mn.ap-southeast-1.rds.amazonaws.com:3306/myblog
#    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password: nam25012003
#    password:
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
    show-sql: true

app:
  security:
      jwt:
        secret-key: dnVob2FpbmFtZHo3NjIzaWxoYWpzbGlmYXNsZmphc2Zqc2phZmxhc2ZzYWQ=
        expiration: 7200000
        refresh-token:
          expiration: 604800000


