spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
    show-sql: true

app:
  security:
      jwt:
        secret-key: dnVob2FpbmFtZHo3NjIzaWxoYWpzbGlmYXNsZmphc2Zqc2phZmxhc2ZzYWQ=
        expiration: 60000
        refresh-token:
          expiration: 300000


