spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
    show-sql: true

