spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true
    show-sql: true

app:
  token:
    secretKey: dnVob2FpbmFtZHo3NjIzaWxoYWpzbGlmYXNsZmphc2Zqc2phZmxhc2ZzYWQ=
    expiration: 86400000

