### Register an account
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstName":"Nam",
  "lastName": "Vuu",
  "address":"xom Đồng Hòa,xã Đại Thắng, huyện Vụ Bản,tỉnh Nam Định",
  "email": "vuhoain3am2ndt@gmail.com",
  "password": "nam123"
}

> {% client.global.set("auth_token", response.body.token); %}


### Add new Post
POST http://localhost:8080/api/v1/posts
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "title": "How to test API in intellij IDEA?",
  "content": "This is a good question.It's on my mood?"
}

##### update a Post
PUT http://localhost:8080/api/v1/posts/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "title": "How toooooo test API in intellij IDEA? updated by userId =2",
  "content": "This is a good question.It's on my mood?"
}

### get a specific post by id
GET http://localhost:8080/api/v1/posts/1
Authorization: Bearer {{auth_token}}
